/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ae96051563e435987cb1f02502d9d8ef)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
