/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c2abdaaa333fde981ecf28696abe73c4)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
