/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9ce1e9f09b0694506e54c940d510f2a7)
interface __BaseEnv_Env {
	DB: D1Database;
	VAPID_PUBLIC_KEY: "BFknaCFpg1G3yB8-5zuBGvgxe4C0yh_4qT1-JNV5sapFB8IOTuc6dacHDSRbZyOHAAGqEpKqMkx6AedzUeBvB4I";
	VAPID_SUBJECT: "mailto:tomoki-chiba@gaji.jp";
	VAPID_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VAPID_PUBLIC_KEY" | "VAPID_SUBJECT" | "VAPID_PRIVATE_KEY">> {}
}
